In [1]:
import numpy as np 

In [2]:
array = np.array([1,2,3,4])

In [14]:
print(np.sqrt(array))
print(np.square(array))

[1.         1.41421356 1.73205081 2.        ]
[ 1  4  9 16]


In [20]:
array2 = np.sqrt(array)
print(array2)

[1.         1.41421356 1.73205081 2.        ]


In [12]:
print(np.ceil(array2)) # round up
print(np.floor(array2)) # round down 
print(np.round(array2)) # round otomatic

[1. 2. 2. 2.]
[1. 1. 1. 2.]
[1. 1. 2. 2.]


In [17]:
print(array-2)
print(array+2)
print(array*2)
print(array/2)
print(array2**2)

[-1  0  1  2]
[3 4 5 6]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[1. 2. 3. 4.]


In [21]:
print(array*np.round(array2))

[1. 2. 6. 8.]


In [22]:
scores = np.array([100,70,56,47,98,69])

In [30]:
for i in scores :
    if i<70:
        print(i)

56
47
69


In [43]:
MATCH=0
find = int(input("Find Matches Below Score: "))
for i in scores < find:
    if i == True:
        MATCH+=1
print(f"Found {MATCH} match! ")

Find Matches Below Score:  71


Found 4 match! 
