In [1]:
import numpy as np

In [3]:
array = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]])

In [7]:
print(array[-1])
print(array[0])

[13 14 15 16]
[1 2 3 4]


In [15]:
print(array[:1]) # array[start:end:step]

[[1 2 3 4]]


In [17]:
print(array[::-1]) # reverse 

[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [22]:
print(array[:,1])

[ 2  6 10 14]


In [41]:
print(array[:, ::-1])

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


In [53]:
print(array[2:3, 1:2]) # row, Column 

[[10]]


In [57]:
print(array[0:1, 0:2]) # first row and 0 to 2 column

[[1 2]]
